### ISSUE TITLE
加载插件失败，可能是插件文件不存在（没有更多的报错信息）

### ISSUE THREAD

**Issue by LovelyA72** [NaruseMioShirakana/MoeVS#30]
我已经安装了所有的前置模型还有两个预制模型。但是当我选择这个模型的时候会有这个报错。
我找不到`LowerCharacters`这个cleaner。请问在哪里可以获取？

**Comment by NaruseMioShirakana** [comment]
这个Cleaner实际上是个不存在的Cleaner，我这边只做了JapaneseCleaner。
如果需要自己制作插件可以查看插件Dll所需要导出的函数。
如果不需要使用插件则可以将Cleaner清空
